Repository DeveloperAcademy-POSTECH/MC2-Team3-SSAK3, pull requests merged in 2022-06, with the labels that each got.

#7 [Merge] #6: firebase messaging & functions 연동
  Taxi/GoogleService-Info.plist
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi.xcodeproj/project.xcworkspace/xcuserdata/jonghopark.xcuserdatad/UserInterfaceState.xcuserstate
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Contents.json
  Taxi/Taxi/Info.plist
  Taxi/Taxi/TaxiApp.swift
  Taxi/Taxi/TaxiRelease.entitlements
Labels: chore, feat, 호종이

#14 [Merge]: Fix Feature Issue template
  .github/ISSUE_TEMPLATE/--feature.md
Labels: chore, docs, 요셉, 아몬드, 아보, 제리

#15 Rename: Fix Project Structure
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi.xcodeproj/project.xcworkspace/xcuserdata/jonghopark.xcuserdatad/UserInterfaceState.xcuserstate
  Taxi/Taxi/Data/.gitkeep
  Taxi/Taxi/Domain/.gitkeep
  Taxi/Taxi/Domain/Model/.gitkeep
  Taxi/Taxi/Domain/Model/Message.swift
  Taxi/Taxi/Domain/Model/Place.swift
  Taxi/Taxi/Domain/Model/TaxiParty.swift
  Taxi/Taxi/Domain/Model/User.swift
  Taxi/Taxi/Domain/UseCase/.gitkeep
  Taxi/Taxi/Presenter/.gitkeep
Labels: chore, 요셉, 아몬드, 아보, 제리

#26 [Merge] #11: Add My Taxi Party Data Layer
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi.xcodeproj/project.xcworkspace/xcuserdata/jonghopark.xcuserdatad/UserInterfaceState.xcuserstate
  Taxi/Taxi/Data/MyTaxiPartyFirebaseDataSource.swift
  Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
  Taxi/Taxi/Domain/Interface/MyTaxiPartyRepository.swift
  Taxi/TaxiTests/MyTaxiPartyRepositoryTest.swift
Labels: test, feat, 호종이

#39 Feat: Add Taxi Party List Use Case Model
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi.xcodeproj/project.xcworkspace/xcuserdata/jonghopark.xcuserdatad/UserInterfaceState.xcuserstate
  Taxi/Taxi/Domain/UseCase/AddTaxiParty.swift
  Taxi/Taxi/Domain/UseCase/GetTaxiParty.swift
  Taxi/Taxi/Domain/UseCase/JoinTaxiParty.swift
Labels: feat, 호종이

#46 Feat: Add Color & textStyle
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Assets.xcassets/background.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/charcoal.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/customBlack.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/customGray.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/customRed.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/customYellow.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/darkGray.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/ktxBlue.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/lightGray.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/postechPink.colorset/Contents.json
  Taxi/Taxi/Extension/ColorExtension.swift
  Taxi/Taxi/Extension/TextStyleExtension.swift
Labels: feat, 조이

#47 [Merge] HOTFIX!: Fix Color.brand to Color.customYellow
  Taxi/Taxi/Component/RoundedButton.swift
Labels: bug, 호종이

#41 [Merge] #38: Add Authenticate use case
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi.xcodeproj/project.xcworkspace/xcuserdata/jonghopark.xcuserdatad/UserInterfaceState.xcuserstate
  Taxi/Taxi/Domain/UseCase/AuthenticateUseCase.swift
  Taxi/Taxi/Domain/UseCase/JoinTaxiParty.swift
Labels: feat, 호종이

#60 [Merge] #42: Add departure place
  Taxi/.swiftlint.yml
  Taxi/Taxi/Domain/Model/Place.swift
Labels: feat, 호종이

#76 Feat: Color & text style
  Taxi/Taxi/Assets.xcassets/customGreen.colorset/Contents.json
  Taxi/Taxi/Assets.xcassets/signUpYellowGray.colorset/Contents.json
  Taxi/Taxi/Extension/ColorExtension.swift
  Taxi/Taxi/Extension/TextStyleExtension.swift
Labels: 아몬드

#92 [Merge] #89 Add deleteProfileImage Method in Authentication
  Taxi/Taxi/Presenter/ViewModel/Authentication.swift
Labels: feat, 아보

#95 [Merge] #27: Add TaxiParty ViewModel to use usecase
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
  Taxi/Taxi/Presenter/ViewModel/AddTaxiPartyViewModel.swift
Labels: feat, 호종이

#98 [Merge] #97 최상단에 User 환경객체 추가
  Taxi/Taxi/TaxiApp.swift
Labels: feat, 아보

#101 [Merge] #100: Add ChattingViewModel Observable Object
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Domain/Model/Message.swift
  Taxi/Taxi/Extension/DateExtension.swift
  Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift
Labels: feat, 호종이

#102 Feat: 캘린더 변경사항 적용
  Taxi/Taxi/Extension/DateExtension.swift
  Taxi/Taxi/Presenter/CalendarView.swift
Labels: feat, 아몬드

#119 [Merge] #118 JoinTaxiPartyViewModel 추가
  Taxi/Taxi/Presenter/ViewModel/JoinTaxiPartyViewModel.swift
Labels: feat, 아보

#123 Feat: calendar modal 로직 구현
  Taxi/Taxi/Presenter/CalendarModal.swift
Labels: feat, 아몬드

#132 Feat: date, day formatter 생성
  Taxi/Taxi/Extension/DateExtension.swift
Labels: feat, 아몬드

#143 Feat: Add LaunchScreen and AppIcon
  Taxi/Launch Screen.storyboard
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Contents.json
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  Taxi/Taxi/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  Taxi/Taxi/Assets.xcassets/launchScreenImage.imageset/Contents.json
  Taxi/Taxi/Assets.xcassets/launchScreenImage.imageset/LaunchScreenFinal.png
Labels: feat, 조이

#144 Feature/#133 Taxi party list destination filtering
  Taxi/Taxi/Presenter/CalendarModal.swift
  Taxi/Taxi/TaxiApp.swift
Labels: feat, 요셉, 아몬드, 제리

#141 Feat: Add Scroll View Reader
  Taxi/Taxi/Presenter/ChatRoomView.swift
  Taxi/Taxi/Presenter/ViewModel/ChattingViewModel.swift
Labels: feat, 호종이

#151 [Merge] #150: Add Rounded Button Loading State
  Taxi/Taxi/Presenter/Component/RoundedButton.swift
Labels: feat, 호종이

#156 [Merge] #153: Fix join taxi party logic
  Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
  Taxi/TaxiTests/AddTaxiPartyUsecaseTest.swift
  Taxi/TaxiTests/ChattingUseCaseTest.swift
  Taxi/TaxiTests/MyTaxiPartyRepositoryTest.swift
  Taxi/TaxiTests/MyTaxiPartyUsecaseTest.swift
  Taxi/TaxiTests/TaxiPartyRepositoryTest.swift
  Taxi/TaxiTests/UserRepositoryTest.swift
Labels: feat, 호종이

#157 [Merge] Add hide keyboard in chattingRoom & Refactoring code
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Data/TaxiPartyFirebaseDataSource.swift
  Taxi/Taxi/Data/UserFirebaseDataSource.swift
  Taxi/Taxi/Domain/Model/FirebaseError.swift
  Taxi/Taxi/Presenter/ChatRoomView.swift
  Taxi/Taxi/Presenter/MainView.swift
  Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift
  Taxi/Taxi/Presenter/ViewModel/Authentication.swift
Labels: feat, refactoring, 호종이

#168 Bug: 달력 모달 tabview 가림, toast message 이슈 해결
  Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift
Labels: bug, 아몬드

#171 [Merge] #166: Fix AddTaxiParty Layout Issue
  Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
Labels: bug, 호종이

#170 [Merge]: Fix Rounded Button Content shape
  Taxi/Taxi/Presenter/Component/RoundedButton.swift
Labels: feat, 호종이
