Repository DeveloperAcademy-POSTECH/MC2-Team3-SSAK3, pull requests merged in 2022-08, with the labels that each got.

#205 Bug: 정보뷰가 닫혀도 블러가 사라지지 않는 버그
  Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift
  Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift
Labels: bug, fix, 아보

#215 [BUG] 채팅방 메시지 정렬 순서 버그
  Taxi/Taxi/Data/MockData/MessageMockData.swift
  Taxi/Taxi/Data/Repository/MyTaxiPartyFirebaseDataSource.swift
  Taxi/Taxi/Data/Repository/TaxiPartyFirebaseDataSource.swift
  Taxi/Taxi/Domain/Model/Message.swift
  Taxi/Taxi/Extension/DateExtension.swift
  Taxi/Taxi/Presenter/Chatting/ChattingViewModel.swift
Labels: bug, refactoring, 호종이

#217 [Feature] Add TaxiParty Live update function in chatting room & refactoring Message struct
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Domain/Model/Message.swift
  Taxi/Taxi/Domain/Model/TaxiParty.swift
  Taxi/Taxi/Extension/DateExtension.swift
  Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift
  Taxi/Taxi/Presenter/Chatting/ChattingViewModel.swift
  Taxi/Taxi/Presenter/Component/PatyListCell.swift
  Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyInfoView.swift
  Taxi/TaxiTests/AuthenticateUsecaseTest.swift
  Taxi/TaxiTests/ChattingUseCaseTest.swift
  Taxi/TaxiTests/ModelTest/MessageTest.swift
  Taxi/TaxiTests/SendEmailUseCaseTest.swift
Labels: feat, refactoring, 호종이

#238 Refactor: Change MyPartyList Vstack to List
  Taxi/Taxi/Presenter/Component/PatyListCell.swift
  Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
  Taxi/Taxi/Presenter/TaxiPartyList/TaxiPartyList.swift
Labels: refactoring, 제리
