Repository DeveloperAcademy-POSTECH/MC2-Team3-SSAK3, pull requests merged in 2022-07, with the labels that each got.

#179 Refactor: change calendar lazyVGrid to VStack and Hstack
  Taxi/Taxi/Presenter/Component/CalendarHelper.swift
  Taxi/Taxi/Presenter/Component/CalendarView.swift
  Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift
Labels: feat

#186 Refactor: refactor login view
  Taxi/Taxi/Extension/StringExtension.swift
  Taxi/Taxi/Presenter/Component/UnderlinedTextField.swift
  Taxi/Taxi/Presenter/SignUp/SignUpCodeView.swift
  Taxi/Taxi/Presenter/SignUp/SignUpNicknameView.swift
Labels: feat

#187 Feat: calendar toast message fade out, modal transition
  Taxi/Taxi/Presenter/TaxiPartyTab/CalendarModal.swift
Labels: feat

#196 Feat: Change OnBoarding Design
  Taxi/Taxi/Assets.xcassets/OnboardingImage/ClockImage.imageset/Contents.json
  Taxi/Taxi/Assets.xcassets/OnboardingImage/ClockImage.imageset/clock.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/ClockImage.imageset/final_clock-1.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/ClockImage.imageset/final_clock-2.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/ClockImage.imageset/final_clock.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/PeopleImage.imageset/Contents.json
  Taxi/Taxi/Assets.xcassets/OnboardingImage/PeopleImage.imageset/final_people-1.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/PeopleImage.imageset/final_people-2.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/PeopleImage.imageset/final_people.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/PeopleImage.imageset/people.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/TaxiImage.imageset/Contents.json
  Taxi/Taxi/Assets.xcassets/OnboardingImage/TaxiImage.imageset/final_taxi-1.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/TaxiImage.imageset/final_taxi-2.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/TaxiImage.imageset/final_taxi.png
  Taxi/Taxi/Assets.xcassets/OnboardingImage/TaxiImage.imageset/taxi.png
  Taxi/Taxi/Presenter/OnboardGroup/OnboardFirstPage.swift
  Taxi/Taxi/Presenter/OnboardGroup/OnboardSecondPage.swift
  Taxi/Taxi/Presenter/OnboardGroup/OnboardThirdPage.swift
Labels: feat, 요셉

#197 Feat: Change Design Refresh UI
  Taxi/Taxi/Assets.xcassets/YellowTaxi.imageset/Contents.json
  Taxi/Taxi/Assets.xcassets/YellowTaxi.imageset/taxiOn-1.svg
  Taxi/Taxi/Assets.xcassets/YellowTaxi.imageset/taxiOn-2.svg
  Taxi/Taxi/Assets.xcassets/YellowTaxi.imageset/taxiOn.svg
  Taxi/Taxi/Presenter/Component/PatyListCell.swift
  Taxi/Taxi/Presenter/TaxiPartyTab/TaxiPartyListView.swift
Labels: feat, 요셉

#194 Bug: Fix Yellow Plus Edit Button 영역 터치 가능
  Taxi/Taxi/Presenter/MyPage/ProfileView.swift
Labels: bug, 요셉
