Repository DeveloperAcademy-POSTECH/MC2-Team3-SSAK3, pull requests merged in 2022-09, with the labels that each got.

#246 [Feature] 메시지 복사 기능
  Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift
Labels: feat, 아보

#253 [Bug] iOS16에서 채팅 입력 칸 색상이 이상하게 나오는 버그
  Taxi/Taxi/Presenter/Chatting/ChatRoomView.swift
Labels: bug, fix, 아보

#255 [Feature] ChatRoomInfo 디자인 시안에 맞게 수정
  Taxi/Taxi/Presenter/Chatting/ChatRoomInfo.swift
Labels: feat, 아보

#256 [Merge] #242: Save password to keychain & fix infinity instance init bug
  Taxi/Taxi.xcodeproj/project.pbxproj
  Taxi/Taxi/Presenter/AddTaxiParty/AddTaxiParty.swift
  Taxi/Taxi/Presenter/MyPage/MyPageView.swift
  Taxi/Taxi/Presenter/MyParty/MyPartyView.swift
  Taxi/Taxi/Presenter/SignIn/SignInViewModel.swift
  Taxi/Taxi/Presenter/System/AppState.swift
  Taxi/Taxi/Presenter/System/MainView.swift
  Taxi/Taxi/Presenter/System/RootView.swift
  Taxi/Taxi/Presenter/System/UserInfoState.swift
  Taxi/Taxi/Presenter/TaxiPartyInfo/TaxiPartyInfo.swift
  Taxi/Taxi/Presenter/TaxiPartyList/ViewModel.swift
Labels: bug, feat, refactoring, 호종이

#260 [Merge] #259 Feat: Add Amplitude
  Taxi/Taxi/Presenter/System/AppState.swift
  Taxi/Taxi/System/TaxiApp.swift
Labels: chore, 호종이
